backend:
  name: github
  repo: hotpinkpoliticalmatrix/wotm
media_folder: static/assets
public_folder: /assets
collections:
  - name: post
    label: Post
    folder: src/Post
    create: true
    fields:
      - { name: slug, label: Slug }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
